// src/persistence/entities/trunk-monitoring.entity.ts
import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn, Index } from 'typeorm';

@Entity('trunk_monitoring')
@Index(['pbx_id', 'trunk_id'])
@Index(['status', 'last_checked'])
export class TrunkMonitoringEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // === IDENTIFICATION (Available from PBX) ===
  @Column({ nullable: true })
  pbx_id: string;

  @Column()
  trunk_id: string;

  @Column({ nullable: true })
  trunk_name: string;

  // === STATUS (Available from PBX API + WebSocket) ===
  @Column({ type: 'int' })
  status: number;  // 1=idle, 2=busy, 41=reg_failed, 42=unreachable

  @Column()
  status_text: string;  // 'idle', 'busy', 'unreachable', 'registration_failed'

  @Column({ type: 'timestamptz' })
  status_changed_at: Date;

  // === CALL METRICS (Available from PBX API) ===
  @Column({ default: 0 })
  active_calls: number;

  // === TIMESTAMPS (Generated by collector) ===
  @Column({ type: 'timestamptz' })
  last_checked: Date;

  // === OPTIONAL (From trunk config, if available) ===
  @Column({ nullable: true })
  protocol: string;  // 'SIP', 'PJSIP'

  @Column({ nullable: true })
  codec: string;  // 'G.711', 'G.729'

  // === PHASE 2 (SBC data - will be populated later) ===
  @Column({ type: 'float', nullable: true })
  current_latency_ms: number;

  @Column({ type: 'float', nullable: true })
  current_bandwidth_in: number;

  @Column({ type: 'float', nullable: true })
  current_bandwidth_out: number;

  // === AUDIT ===
  @CreateDateColumn({ type: 'timestamptz' })
  created_at: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updated_at: Date;

  // Add these fields to the existing entity

  @Column({ type: 'float', nullable: true })
  ami_latency_ms: number;  // From AMI SIPshowpeer

  @Column({ type: 'float', nullable: true })
  ami_jitter_ms: number;   // From AMI SIPshowpeer

  @Column({ type: 'float', nullable: true })
  ami_packet_loss_pct: number;  // From AMI SIPshowpeer

  @Column({ nullable: true })
  ami_status: string;  // 'Registered', 'Unreachable'

  @Column({ type: 'timestamptz', nullable: true })
  ami_last_checked: Date;  // When AMI data was last updated
}